### ISSUE TITLE
Error on require using yarn2 pnp on fresh install

### ISSUE THREAD

**Issue by garcianavalon** [graphile/postgraphile#1440]
### Summary

After migrating my project to use Yarn 2 and PnP requiring Postgraphile fails. I've managed to replicate the bug on a minimum setup.
```
Uncaught:
Error: graphile-utils tried to access graphile-build-pg (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: graphile-build-pg (via "graphile-build-pg")
Required by: graphile-utils@virtual:b4c5999b9717b0ae1a7ac87dc1db0246cd8f7e1dcc4994142c1128cfd338ab5f0e2007151a293597266c35c20993c1ef4f68e817d9bad399170bec602168a564#npm:4.11.2 (via /Users/garcianavalon/deleteme/yarn2postgraphile/.yarn/$$virtual/graphile-utils-virtual-d09b9026bf/0/cache/graphile-utils-npm-4.11.2-8f5ec4fc95-d1e2b40727.zip/node_modules/graphile-utils/node8plus/)
Ancestor breaking the chain: postgraphile@npm:4.11.0

Require stack:
- /Users/garcianavalon/deleteme/yarn2postgraphile/.yarn/$$virtual/graphile-utils-virtual-d09b9026bf/0/cache/graphile-utils-npm-4.11.2-8f5ec4fc95-d1e2b40727.zip/node_modules/graphile-utils/node8plus/fieldHelpers.js
- /Users/garcianavalon/deleteme/yarn2postgraphile/.yarn/$$virtual/graphile-utils-virtual-d09b9026bf/0/cache/graphile-utils-npm-4.11.2-8f5ec4fc95-d1e2b40727.zip/node_modules/graphile-utils/node8plus/makeExtendSchemaPlugin.js
- /Users/garcianavalon/deleteme/yarn2postgraphile/.yarn/$$virtual/graphile-utils-virtual-d09b9026bf/0/cache/graphile-utils-npm-4.11.2-8f5ec4fc95-d1e2b40727.zip/node_modules/graphile-utils/node8plus/index.js
- /Users/garcianavalon/deleteme/yarn2postgraphile/.yarn/cache/postgraphile-npm-4.11.0-b4c5999b97-6b96be303f.zip/node_modules/postgraphile/build/index.js
- /Users/garcianavalon/deleteme/yarn2postgraphile/.yarn/cache/postgraphile-npm-4.11.0-b4c5999b97-6b96be303f.zip/node_modules/postgraphile/index.js
- <repl>
    at internalTools_makeError (/Users/garcianavalon/deleteme/yarn2postgraphile/.pnp.js:6127:34)
    at resolveToUnqualified (/Users/garcianavalon/deleteme/yarn2postgraphile/.pnp.js:7059:23)
    at resolveRequest (/Users/garcianavalon/deleteme/yarn2postgraphile/.pnp.js:7184:29)
    at Object.resolveRequest (/Users/garcianavalon/deleteme/yarn2postgraphile/.pnp.js:7262:26)
    at Function.external_module_.Module._resolveFilename (/Users/garcianavalon/deleteme/yarn2postgraphile/.pnp.js:6360:34)
    at Function.external_module_.Module._load (/Users/garcianavalon/deleteme/yarn2postgraphile/.pnp.js:6225:48)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```
### Steps to reproduce

```bash
yarn init
yarn set version berry
yarn add postgraphile
yarn node
> require('postgraphile')
```
### Expected results

require works correctly

### Actual results

`Error: graphile-utils tried to access graphile-build-pg (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.`

### Additional context

 node --version
v12.18.2
"postgraphile": "^4.11.0"

### Possible Solution

Add the missing dependencies to package.json

Temporary fix: using [packageExtensions](https://next.yarnpkg.com/configuration/yarnrc#packageExtensions)
```yaml
# .yarnrc.yml
packageExtensions:
  "graphile-utils@*":
    dependencies:
      "graphile-build-pg": "^4.11.2"
  "graphile-build-pg@*":
    dependencies:
       "graphql": "^15.5.0"
       "pg": "^8.5.1"
```

**Comment by garcianavalon** [comment]
I've managed to fix the issue using packageExtensions to add the missing dependencies
```yaml
# .yarnrc.yml
packageExtensions:
  "graphile-utils@*":
    dependencies:
      "graphile-build-pg": "^4.11.2"
  "graphile-build-pg@*":
    dependencies:
       "graphql": "^15.5.0"
       "pg": "^8.5.1"
```

The final fix would be to update the package.json of `graphile-utils` and `graphile-build-pg` to add the missing dependencies.

@benjie I can open a PR for them or would you rather check it yourself?
