### ISSUE TITLE
Docker issue.

### ISSUE THREAD

**Issue by stefan1968** [graphile/postgraphile#717]
I'm submitting a ... 

* [x ] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: Any.

Minimal SQL file that can be loaded into a clean database:

```sql

```

Steps to reproduce:

I'm running postgraphile in a docker container (via express) it works locally, but no matter what version of postgraphile or postgraphql i use, it seems to not correct or get the initial schema. I know its working as i can get the graphiql UI up, but for some reason it can't fetch the schema when its dockerized.
It just seems to be stuck getting the initial graphQL schema introspection query.
<img width="1303" alt="screen shot 2018-03-16 at 19 46 46" src="https://user-images.githubusercontent.com/5500038/37541542-edf1ab5a-2952-11e8-9650-5e3120916ae8.png">
<img width="1417" alt="screen shot 2018-03-16 at 19 46 13" src="https://user-images.githubusercontent.com/5500038/37541543-ee09f5e8-2952-11e8-8437-1e569117ca88.png">

Current behavior:

Expected behavior:

**Comment by stefan1968** [comment]
I suspect it's because postgraphile is running at localhost, not 0.0.0.0

There is a --host flag, but is this available in the options object when used as middleware?

**Comment by stefan1968** [comment]
Actually, i changed the code express code so it should be listening on 0.0.0.0

But no avail.

app.listen(config.postgraphile.port || 5000, '0.0.0.0');

**Comment by kron4eg** [comment]
@stefan1968 you also need to map exposed container port (5000) to your machine. If you use docker-compose (which I recommend to do), docker-compose.yml will something look like this:

```
version: '3'
services:
  api:
    build:
      context: .
    environment:
      DATABASE_URL: "postgres://postgres@postgres/mydb"
    ports:
    - "5000:5000"
    command:
    - yarn
    - run
    - start
    depends_on:
    - postgres

  postgres:
    image: "postgres:alpine"
    ports:
    - "5432:5432"
    volumes:
    - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "mydb"

volumes:
  db-data:
```

Or use `docker run -p`

**Comment by stefan1968** [comment]
```
postgraphile:
    build:
      context: ./graphql
      dockerfile: Dockerfile.graphql
    network_mode: bridge
    container_name: graphql-container
    environment:
      - VIRTUAL_HOST=graphql.originapi.com
      - NODE_ENV=production
      - PROD=true
    ports:
      - "5000:5000"
    command: "npm run start"
```

As you see, it's exposed. So, still not sure what is happening. Going to try running it directly, not as express middleware.
